const express = require ('express')
const ConnectDB = require('./config/ConnectDB')
const ProfileRoute = require('./Routes/ProfileRoute')
const app = express()
require ('dotenv').config()
ConnectDB()
app.use(express.json())
app.use('/Profile',ProfileRoute)
app.listen(process.env.port,console.log(`serveur ouvert sur le port ${process.env.port}`))